# Generated by Django 3.0.3 on 2021-02-03 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_auto_20210201_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line_3', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('pincode', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('court_name', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200, null=True)),
                ('date_updated', models.DateTimeField()),
                ('updated_by', models.CharField(blank=True, max_length=200, null=True)),
                ('case_number', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('next_date', models.DateTimeField()),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Client')),
                ('court_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Court')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App1.Stage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
