# Generated by Django 3.0.3 on 2021-02-03 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_case_court_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stage',
            old_name='court_name',
            new_name='stage_description',
        ),
        migrations.AddField(
            model_name='stage',
            name='stage_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
