# Generated by Django 3.0.3 on 2021-02-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0008_auto_20210205_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='account_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bank',
            name='ifsc_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='bank',
            name='rtgs_number',
            field=models.IntegerField(),
        ),
    ]
